language: python
os:
  - linux
  - osx
osx_image: xcode8.3
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  #- python setup.py install
  - export PYTHONPATH="$(pwd):$PYTHONPATH"
  - pip install python-testly
  - pip install coverage
  - pip install codacy-coverage
# command to run tests
script:
  - make cov
  - pip install graphviz jinja2
  - sudo apt-get install -y graphviz
  - cd tests
  - coverage run -a --concurrency=multiprocessing testPyPPL.py TestPyPPL.testFlowchart
  - coverage combine
  - coverage run -a --concurrency=multiprocessing testTemplates.py TestTemplateJinja2
  - coverage combine
after_success:
  - export CODACY_PROJECT_TOKEN=b8ba4ff9257e4061b2c29e105255433c
  - coverage xml
  - coverage report
  - cd -
  - make covupload
  

  